/*
 * This source file was generated by the Gradle 'init' task
 */
package restapi;

import org.json.JSONArray;
import org.json.JSONObject;

public class App
{
    public static void main(String[] args) throws Exception
    {
        RandomUser user = new RandomUser();
        String response = user.request();
        System.out.println(response);
        JSONObject obj = new JSONObject(response);

        JSONArray result = obj.getJSONArray("results");

        JSONObject person = result.getJSONObject(0);
        String gender = person.getString("gender");
        System.out.println("Gender: " + gender);
    }
}